# Test Colab Bootstrap and Badge
This demos some code to facilitate running notebooks in Colab rather than a conda environment.

Run the next two cells for set up.

In [ ]:
# --- Unified bootstrap cell for local + Colab ---
import os, pathlib, subprocess, sys, importlib

# --- Required metadata for the header ---
os.environ["BOOT_ORG"]   = "QMCSoftware"   # GitHub org
os.environ["BOOT_REPO"]  = "MATH565Fall2025"  # This repo name
os.environ["NB_PATH"]    = "notebooks/TestingDemos/TestColabBootstrapAndBadge.ipynb"
os.environ["BOOT_BRANCH"] = "main"         # Target branch
os.environ["NOTEBOOK_HEADER_AUTORUN"] = "0"  # Avoid double badge
os.environ["AUTO_PLOT_PREFS"] = "1"      #apply plotting preferences

# --- Colab: clone repo if missing ---
if "COLAB_RELEASE_TAG" in os.environ or "COLAB_GPU" in os.environ:
    repo_dir = pathlib.Path(f"/content/{os.environ['BOOT_REPO']}")
    if not repo_dir.exists():
        subprocess.check_call([
            "git","clone","--depth","1","--recurse-submodules",
            "-b", os.environ["BOOT_BRANCH"],
            f"https://github.com/{os.environ['BOOT_ORG']}/{os.environ['BOOT_REPO']}.git",
            str(repo_dir)
        ])
    sys.path.insert(0, str(repo_dir / "utils"))
    try:
        os.chdir(repo_dir)
    except Exception:
        pass
else:
    # Local: add utils to path
    repo_root = subprocess.check_output(["git","rev-parse","--show-toplevel"], text=True).strip()
    sys.path.insert(0, repo_root + "/utils")

# --- Load notebook header ---
import notebook_header
importlib.reload(notebook_header)
notebook_header.main()

In [2]:
# ---- Sanity check: matplotlib mode ----
print("usetex?", plt.rcParams.get("text.usetex"))

# ---- Sanity check: qmcpy ----
n = 2**10
x = qp.Sobol(3).gen_samples(n)
print("Generated", n, "samples in 3D Sobol sequence:")
print(x[:5])  # Print first 5 samples for brevity
variance = np.var(x, axis=0)
print("Variance of all samples:", variance)

usetex? False
Generated 1024 samples in 3D Sobol sequence:
[[0.56713753 0.19997895 0.39988672]
 [0.25635642 0.86015947 0.72556043]
 [0.75192316 0.52840807 0.82534664]
 [0.06618446 0.40734073 0.04945797]
 [0.70951578 0.8883414  0.17224803]]
Variance of all samples: [0.08333345 0.08333333 0.08333333]


In [ ]:
# ---- Sanity check: matplotlib preferences ----

# Check some rcParams directly
print("Figure size:", plt.rcParams['figure.figsize'])
print("Figure DPI:", plt.rcParams['figure.dpi'])
print("Font size:", plt.rcParams['font.size'])
print("Grid enabled:", plt.rcParams['axes.grid'])
print("Line width:", plt.rcParams['lines.linewidth'])
print("Math fontset:", plt.rcParams['mathtext.fontset'])

# Quick test plot
x = np.linspace(0, 2*np.pi, 200)
y = np.sin(x)
plt.plot(x, np.sin(2*np.pi*x), label=r"$\vx,\, \norm{x},\, \Ex[\vx]$")
plt.title("Sanity Check: Plot Preferences")
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.show()

Figure size: [6.0, 4.0]
Figure DPI: 120.0
Font size: 12.0
Grid enabled: True
Line width: 2.0
Math fontset: cm


ValueError: 
$x$
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)

<Figure size 720x480 with 1 Axes>